---
- name: hadoop services started
  hosts: nodes
  gather_facts: false
  become: true
  tasks:
  - name: data node service exists 
    stat: path=/lib/systemd/system/hdfs-datanode.service
    register: datanode_status
  - name: start datanode
    service: 
      name: hdfs-datanode
      state: started
    when: datanode_status.stat.exists
  - name: name node service exists 
    stat: path=/lib/systemd/system/hdfs-namenode.service
    register: namenode_status
  - name: start namenode
    service: 
      name: hdfs-namenode
      state: started
    when: namenode_status.stat.exists
  - name: resource manager service exists 
    stat: path=/lib/systemd/system/yarn-resourcemanager.service
    register: yrm_status
  - name: start yarn resource manager
    service: 
      name: yarn-resourcemanager
      state: started
    when: yrm_status.stat.exists
  - name: yarn proxy server service exists 
    stat: path=/lib/systemd/system/yarn-proxyserver.service
    register: yps_status
  - name: start yarn proxyserver
    service: 
      name: yarn-proxyserver
      state: started
    when: yps_status.stat.exists
  - name: yarn node manager service exists 
    stat: path=/lib/systemd/system/yarn-nodemanager.service
    register: ynm_status
  - name: start node manager
    service: 
      name: yarn-nodemanager
      state: started
    when: ynm_status.stat.exists
  - name: mariadb service exists 
    stat: path=/lib/systemd/system/mariadb.service
    register: mdb_status
  - name: start maria db
    service: 
      name: mariadb
      state: started
    when: mdb_status.stat.exists
  - name: airflow-scheduler service exists 
    stat: path=/lib/systemd/system/airflow-scheduler.service
    register: ae_status
  - name: start airflow scheduler
    service: 
      name: airflow-scheduler
      state: started
    when: ae_status.stat.exists
  - name: airflow-webserver service exists 
    stat: path=/lib/systemd/system/airflow-webserver.service
    register: aw_status
  - name: start airflow scheduler
    service: 
      name: airflow-webserver
      state: started
    when: aw_status.stat.exists
